services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tp-app:latest
    networks:
      - evaluation_network
    environment:
      - APP_ENV=prod
      - PORT=5000
networks:
  evaluation_network:
    external: true