name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test
        run: docker build -t tp-app:latest ./app 

  terraform:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init & Plan
        run: |
          cd infra/terraform
          terraform init
          terraform plan

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Install Ansible & Docker Collection
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Build et Deploy via Ansible
        run: |
          cd infra/ansible
          # Empêche l'erreur du plugin de callback YAML supprimé
          export ANSIBLE_STDOUT_CALLBACK=default
          ansible-playbook site.yml
        env:
          APP_ENV: "prod"
          PORT: 5000

      - name: Vérification du Healthcheck
        run: curl --fail http://localhost:8080/health