name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: check du code
        uses: actions/checkout@v4

      - name: Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Installation d'Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Installation de Docker collection et d'ansible
        run: ansible-galaxy collection install community.docker

      - name: Build et Deploy via Ansible
        run: |
          cd infra/ansible
          ansible-playbook site.yml
        env:
          APP_ENV: "prod"
          PORT: 5000

      - name: VÃ©rification du Healthcheck
        run: curl --fail http://localhost:8080/health #
